---


- name: install mpd
  gather_facts: no
  hosts: all
  become: yes
  tasks:
  - name: install mpd dep
    ansible.builtin.apt:
      name:
      - meson
      - g++
      - libpcre3-dev
      - libmad0-dev
      - libmpg123-dev
      - libid3tag0-dev
      - libflac-dev
      - libvorbis-dev
      - libopus-dev
      - libogg-dev
      - libadplug-dev
      - libaudiofile-dev
      - libsndfile1-dev
      - libfaad-dev
      - libfluidsynth-dev
      - libgme-dev
      - libmikmod-dev
      - libmodplug-dev
      - libmpcdec-dev
      - libwavpack-dev
      - libwildmidi-dev
      - libsidplay2-dev
      - libsidutils-dev
      - libresid-builder-dev
      - libavcodec-dev
      - libavformat-dev
      - libmp3lame-dev
      - libtwolame-dev
      - libshine-dev
      - libsamplerate0-dev
      - libsoxr-dev
      - libbz2-dev
      - libcdio-paranoia-dev
      - libiso9660-dev
      - libmms-dev
      - libzzip-dev
      - libcurl4-gnutls-dev
      - libyajl-dev
      - libexpat-dev
      - libasound2-dev
      - libao-dev
      - libjack-jackd2-dev
      - libopenal-dev
      - libpulse-dev
      - libshout3-dev
      - libsndio-dev
      - libmpdclient-dev
      - libnfs-dev
      - libupnp-dev
      - libavahi-client-dev
      - libsqlite3-dev
      - libsystemd-dev
      - libgtest-dev
      - libboost-dev
      - libicu-dev
      - libchromaprint-dev
      - libgcrypt20-dev
  - name: create working dir
    ansible.builtin.file:
      path: /usr/local/src/mpd
      state: directory
      mode: '0755'
  - name: fetch mpd src
    ansible.builtin.get_url:
      url: https://www.musicpd.org/download/mpd/{{ mpd_version.rsplit('.', 1)[0] }}/mpd-{{ mpd_version }}.tar.xz
      dest: /usr/local/src/mpd/mpd-{{ mpd_version }}.tar.xz
  - name: extract mpd src
    ansible.builtin.unarchive:
      src: /usr/local/src/mpd/mpd-{{ mpd_version }}.tar.xz
      remote_src: yes
      dest: /usr/local/src/mpd
      creates: /usr/local/src/mpd/mpd-{{ mpd_version }}
  - name: configure mpd
    ansible.builtin.command:
      chdir: /usr/local/src/mpd/mpd-{{ mpd_version }}
      argv:
      - meson
      - .
      - output/release
      - --buildtype=debugoptimized
      -  -Db_ndebug=true
      creates: /usr/local/src/mpd/mpd-{{ mpd_version }}/output/release
  - name: build mpd
    ansible.builtin.command:
      chdir: /usr/local/src/mpd/mpd-{{ mpd_version }}
      argv:
      - ninja
      - -C
      - output/release
      - -j
      - '1'
      creates: /usr/local/src/mpd/mpd-{{ mpd_version }}/output/release/mpd
  - name: install mpd
    ansible.builtin.command:
      chdir: /usr/local/src/mpd/mpd-{{ mpd_version }}
      argv:
      - ninja
      - -C
      - output/release
      - install
  - name: configure mpd starts after mount
    ansible.builtin.lineinfile:
      path: /usr/local/lib/systemd/system/mpd.service
      regexp: '^After=network.target'
      line: 'After=network.target sound.target mnt-wibble.mount'
  - name: create mpd user
    ansible.builtin.user:
      name: mpd
      shell: /sbin/nologin
      uid: 122
      group: audio
  - name: create default mpd directory
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
      owner: mpd
      group: audio
    loop:
    - /var/lib/mpd
    - /var/log/mpd
    - /run/mpd
  - name: create default mpd conf
    ansible.builtin.copy:
      force: no
      src: mpd.conf.default
      dest: /usr/local/etc/mpd.conf
      mode: '0644'
      owner: root
      group: root
  - name: start mpd
    ansible.builtin.systemd:
      name: mpd
      state: restarted
      enabled: yes
      daemon_reload: yes
