---

- name: setup rpi audio config
  gather_facts: no
  hosts: all
  become: yes
  tasks:
  - name: turn off
    ansible.builtin.replace:
      dest: "{{ boot_config_txt | default('/boot/config.txt') }}"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    with_items:
    - regexp: '^ *dtoverlay=(?!hifiberry-dacplus)'
      replace: '# dtoverlay='
    - regexp: '^ *dtparam=audio=on'
      replace: '# dtparam=audio=on'
    notify:
    - reboot
  - name: "enable SB32+PRO DoP"
    ansible.builtin.lineinfile:
      path: "{{ boot_config_txt | default('/boot/config.txt') }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
    - regexp: 'dtparam=i2c_arm'
      line: 'dtparam=i2c_arm=on'
    - regexp: 'dtparam=i2s'
      line: 'dtparam=i2s=on'
    - regexp: '^ *dtoverlay='
      line: 'dtoverlay=hifiberry-dacplus'
    notify:
    - reboot
  - name: create mpd conf
    ansible.builtin.copy:
      src: rpi/mpd.output.conf
      dest: /etc/mpd.output.conf
      mode: '0644'
      owner: root
      group: root
    notify:
    - restart mpd
  - name: include mpd conf
    ansible.builtin.lineinfile:
      path: /etc/mpd.conf
      regexp: 'include "/etc/mpd.output.conf"'
      line: 'include "/etc/mpd.output.conf"'
    notify:
    - restart mpd
  handlers:
  - name: reboot
    ansible.builtin.reboot:
  - name: restart mpd
    ansible.builtin.systemd:
      name: mpd
      state: restarted
      daemon_reload: yes
