---

- name: setup rpi audio config
  gather_facts: no
  hosts: all
  become: yes
  tasks:
  - name: setup /boot/config.txt
    ansible.builtin.copy:
      src: rpi/config.txt
      dest: /boot/config.txt
      mode: '0751'
      owner: root
      group: root
    notify:
    - reboot
  - name: create mpd conf
    ansible.builtin.copy:
      src: rpi/mpd.output.conf
      dest: /etc/mpd.output.conf
      mode: '0644'
      owner: root
      group: root
    notify:
    - restart mpd
  - name: include mpd conf
    ansible.builtin.lineinfile:
      path: /etc/mpd.conf
      regexp: 'include "/etc/mpd.output.conf"'
      line: 'include "/etc/mpd.output.conf"'
    notify:
    - restart mpd
  handlers:
  - name: reboot
    ansible.builtin.reboot:
  - name: restart mpd
    ansible.builtin.systemd:
      name: mpd
      state: restarted
      daemon_reload: yes
