---

- name: setup rpi audio config
  gather_facts: no
  hosts: all
  become: yes
  tasks:
  - name: setup /boot/config.txt
    ansible.builtin.copy:
      src: rpi/config.txt
      dest: /boot/config.txt
      mode: '0751'
      owner: root
      group: root
    notify:
    - reboot
  - name: set audio group limits
    ansible.builtin.copy:
      src: rpi/audio.limits.conf
      dest: /etc/security/limits.d/audio.limits.conf
      mode: '0644'
      owner: root
      group: root
    notify:
    - reboot
  - name: stop unused services for audio
    ansible.builtin.systemd:
      name: '{{ item }}'
      state: stopped
      enabled: no
    loop:
    - keyboard-setup # keyboard layout
    - dphys-swapfile # swap
    - triggerhappy   # hotkey
    - wpa_supplicant # wifi
  - name: set rpi sysctl
    ansible.builtin.copy:
      src: rpi/rpi.sysctl.conf
      dest: /etc/sysctl.d/rpi.sysctl.conf
      mode: '0644'
      owner: root
      group: root
    notify:
    - reload sysctl
  - name: create mpd conf
    ansible.builtin.copy:
      src: rpi/mpd.output.conf
      dest: /etc/mpd.output.conf
      mode: '0644'
      owner: root
      group: root
    notify:
    - restart mpd
  - name: include mpd conf
    ansible.builtin.lineinfile:
      path: /etc/mpd.conf
      regexp: 'include "/etc/mpd.output.conf"'
      line: 'include "/etc/mpd.output.conf"'
    notify:
    - restart mpd
  - name: use google dns
    ansible.builtin.lineinfile:
      path: /etc/dhcpcd.conf
      regexp: 'static domain_name_servers='
      line: 'static domain_name_servers=8.8.8.8 8.8.4.4'
    notify:
    - reboot
  handlers:
  - name: reboot
    ansible.builtin.reboot:
  - name: reload sysctl
    ansible.builtin.command:
      argv:
      - sysctl
      - -p
  - name: restart mpd
    ansible.builtin.systemd:
      name: mpd
      state: restarted
      daemon_reload: yes
